version: '3.3'

services:
  # container for executing config import scripts for setting up the validator-orchestrator
  validator-orchestrator-config-importer:
    container_name: validator-orchestrator-config-importer
    image: jembi/instantohie-config-importer
    restart: on-failure
    environment:
      MEDIATOR_HOST_NAME: 'validator-orchestrator'
      MEDIATOR_API_PORT: 3003
      MEDIATOR_API_PATH: /endpoints
    volumes:
      - type: bind
        source: ./services-config/volume/validator-orchestrator
        target: /importer
    # This command will only attempt to import the service config when the mediator is up and running
    command: sh -c "wait-on -t 60000 http-get://validator-orchestrator:3003/uptime && sleep 1 && node serviceConfig.js"
    depends_on:
      - validator-orchestrator

  # container for executing config import scripts for setting up the populator
  populator-config-importer:
    container_name: populator-config-importer
    image: jembi/instantohie-config-importer
    restart: on-failure
    environment:
      MEDIATOR_HOST_NAME: 'populator'
      MEDIATOR_API_PORT: 3003
      MEDIATOR_API_PATH: /endpoints
    volumes:
      - type: bind
        source: ./services-config/volume/populator
        target: /importer
    # This command will only attempt to import the service config when the mediator is up and running
    command: sh -c "wait-on -t 60000 http-get://populator:3003/uptime && sleep 1 && node serviceConfig.js"
    depends_on:
      - populator

  # container for executing config import scripts for setting up the facility-cache
  facility-cache-config-importer:
    container_name: facility-cache-config-importer
    image: jembi/instantohie-config-importer
    restart: on-failure
    environment:
      MEDIATOR_HOST_NAME: 'facility-cache'
      MEDIATOR_API_PORT: 3005
    volumes:
      - type: bind
        source: ./services-config/volume/facility-cache
        target: /importer
    # This command will only attempt to import the service config when the mediator is up and running
    command: sh -c "node serviceConfig.js"
    depends_on:
      - facility-cache

  # container for executing config import scripts for setting up the facility-cache
  file-queue-config-importer:
    container_name: file-queue-config-importer
    image: jembi/instantohie-config-importer
    restart: on-failure
    environment:
      MEDIATOR_HOST_NAME: 'file-queue'
      MEDIATOR_API_PORT: 4003
    volumes:
      - type: bind
        source: ./services-config/volume/file-queue
        target: /importer
    # This command will only attempt to import the service config when the mediator is up and running
    command: sh -c "node serviceConfig.js"
    depends_on:
      - file-queue
