version: '3.3'

services:
  validator-orchestrator:
    image: jembi/openhim-mediator-mapping:v1.0.1
    container_name: validator-orchestrator
    expose:
      - 3003
    environment:
      - OPENHIM_URL=https://openhim-core:8080
      - OPENHIM_USERNAME=root@openhim.org
      - OPENHIM_PASSWORD=password
      - MONGO_URL=mongodb://mongo-1:27017,mongo-2:27017,mongo-3:27017/validator-orchestrator?replicaSet=mongo-set
      - PARSER_LIMIT=10mb
      - MEDIATOR_URN=urn:mediator:validator-orchestrator

  populator:
    image: jembi/openhim-mediator-mapping:v1.0.1
    container_name: populator
    expose:
      - 3003
    environment:
      - OPENHIM_URL=https://openhim-core:8080
      - OPENHIM_USERNAME=root@openhim.org
      - OPENHIM_PASSWORD=password
      - MONGO_URL=mongodb://mongo-1:27017,mongo-2:27017,mongo-3:27017/populator?replicaSet=mongo-set
      - PARSER_LIMIT=10mb
      - MEDIATOR_URN=urn:mediator:populator

  file-queue:
    image: jembi/openhim-mediator-file-queue:latest
    container_name: file-queue
    expose:
      - 4002
    environment:
      - SERVER_PORT=4002
      - API_URL=https://openhim-core:8080
      - API_USERNAME=root@openhim.org
      - API_PASSWORD=password
      - HEARTBEAT=true
      - LOG_LEVEL=info
      - NODE_TLS_REJECT_UNAUTHORIZED=0
      - SERVER_PORT=4003
      - TRUST_SELF_SIGNED=true
    volumes:
      - ./file-queue-mediator.json:/opt/openhim-mediator-file-queue/config/mediator.json

  facility-cache:
    image: jembi/facility-cache:v5.0.0
    container_name: facility-cache
    expose:
      - 3500
    environment:
      - SERVER_PORT=3500
      - SERVER_HOSTNAME=facility-cache
      - OPENHIM_URL=https://openhim-core:8080
      - OPENHIM_USERNAME=root@openhim.org
      - OPENHIM_PASSWORD=password
      - LOGGING_LEVEL=info
      - REGISTER_MEDIATOR=true
      - TRUSTED_SELF_SIGNED=true
