version: '3.3'

volumes:
  dhis-volume:

services:
  mongo-1:
    image: mongo:4.2
    container_name: mongo-1
    volumes:
      - './data/mongo1:/data/db'
    command:
        - --replSet
        - mongo-set

  mongo-2:
    image: mongo:4.2
    container_name: mongo-2
    volumes:
      - './data/mongo2:/data/db'
    command:
        - --replSet
        - mongo-set

  mongo-3:
    image: mongo:4.2
    container_name: mongo-3
    volumes:
      - './data/mongo3:/data/db'
    command:
        - --replSet
        - mongo-set

  db:
    container_name: dhis-postgres
    image: mdillon/postgis:10-alpine
    command: postgres -c max_locks_per_transaction=100
    environment:
      PGDATA: /var/lib/postgresql/data/pgdata
      POSTGRES_USER: dhis
      POSTGRES_DB: dhis2
      POSTGRES_PASSWORD: dhis
    volumes:
      - dhis-volume:/var/lib/postgresql/data
