version: '3.3'

networks:
  default:
    external:
      name: docker_default

services:
  # container for executing config import scripts for setting up the facility-cache
  facility-cache-config-importer:
    container_name: facility-cache-config-importer
    image: jembi/instantohie-config-importer:v1.0.0
    restart: on-failure
    environment:
      OPENHIM_API_HOSTNAME: 'openhim-core'
      OPENHIM_API_PORT: 8080
      OPENHIM_API_USERNAME: 'root@openhim.org'
      OPENHIM_API_PASSWORD: 'password'
      OPENHIM_MEDIATOR_URN: 'urn:mediator:facility-cache'
      # Reject unauthorised is only needed if the OpenHIM's SSL is not setup
      NODE_TLS_REJECT_UNAUTHORIZED: 0
    volumes:
      - type: bind
        source: ./volume
        target: /importer
    # This command will only attempt to import the OpenHIM config when the heartbeat responds with a 2xx
    command: sh -c "wait-on -t 60000 https-get://openhim-core:8080/heartbeat && node serviceConfig.js"
