version: '3.3'

networks:
  default:
    external:
      name: docker_default

services:
  # container for executing config import scripts for setting up the validator-orchestrator
  validator-orchestrator-config-importer:
    container_name: validator-orchestrator-config-importer
    image: jembi/instantohie-config-importer:v1.0.0
    restart: on-failure
    environment:
      MEDIATOR_HOST_NAME: 'validator-orchestrator'
      MEDIATOR_API_PORT: 3003
      MEDIATOR_API_PATH: /endpoints
    volumes:
      - type: bind
        source: ./volume
        target: /importer
    # This command will only attempt to import the service config when the mediator is up and running
    command: sh -c "wait-on -t 60000 http-get://validator-orchestrator:3003/uptime && node -e 'require(\"./metadata.js\").importMetaData()'"
