version: '3.3'

networks:
  default:
    external:
      name: docker_default

services:
  metadata-importer-dhis2:
    container_name: metadata-importer-dhis2
    image: jembi/instantohie-config-importer:v1.0.0
    restart: on-failure
    volumes:
      - type: bind
        source: ./volume
        target: /importer
    command: sh -c "wait-on -t 60000 http-get://dhis-web:8080 && node -e 'require(\"./metadata.js\").importMetaData()'"
